// Generated by gencpp from file gabor_runtime_monitoring/Average.msg
// DO NOT EDIT!


#ifndef GABOR_RUNTIME_MONITORING_MESSAGE_AVERAGE_H
#define GABOR_RUNTIME_MONITORING_MESSAGE_AVERAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gabor_runtime_monitoring
{
template <class ContainerAllocator>
struct Average_
{
  typedef Average_<ContainerAllocator> Type;

  Average_()
    : average(0.0)  {
    }
  Average_(const ContainerAllocator& _alloc)
    : average(0.0)  {
  (void)_alloc;
    }



   typedef double _average_type;
  _average_type average;





  typedef boost::shared_ptr< ::gabor_runtime_monitoring::Average_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gabor_runtime_monitoring::Average_<ContainerAllocator> const> ConstPtr;

}; // struct Average_

typedef ::gabor_runtime_monitoring::Average_<std::allocator<void> > Average;

typedef boost::shared_ptr< ::gabor_runtime_monitoring::Average > AveragePtr;
typedef boost::shared_ptr< ::gabor_runtime_monitoring::Average const> AverageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gabor_runtime_monitoring::Average_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gabor_runtime_monitoring

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gabor_runtime_monitoring': ['/home/chris/Documents/f110-2019-a/chris/gabor_ws/src/gabor_runtime_monitoring/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gabor_runtime_monitoring::Average_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gabor_runtime_monitoring::Average_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gabor_runtime_monitoring::Average_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
{
  static const char* value()
  {
    return "711be0a796b85a8a1e109ae6a26ad085";
  }

  static const char* value(const ::gabor_runtime_monitoring::Average_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x711be0a796b85a8aULL;
  static const uint64_t static_value2 = 0x1e109ae6a26ad085ULL;
};

template<class ContainerAllocator>
struct DataType< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gabor_runtime_monitoring/Average";
  }

  static const char* value(const ::gabor_runtime_monitoring::Average_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 average\n\
";
  }

  static const char* value(const ::gabor_runtime_monitoring::Average_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.average);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Average_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gabor_runtime_monitoring::Average_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gabor_runtime_monitoring::Average_<ContainerAllocator>& v)
  {
    s << indent << "average: ";
    Printer<double>::stream(s, indent + "  ", v.average);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GABOR_RUNTIME_MONITORING_MESSAGE_AVERAGE_H
